# Generated by Django 4.1.6 on 2024-02-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lecture',
        ),
    ]
