# Generated by Django 4.1.6 on 2024-02-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=111111, max_length=44),
            preserve_default=False,
        ),
    ]
