# Generated by Django 4.1.6 on 2024-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_course_created_at_course_upload_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_ru',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_uz',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
