# Generated by Django 4.1.6 on 2024-02-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_body_en_course_body_ru_course_body_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level_uz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_uz',
        ),
    ]
