# Generated by Django 5.0 on 2024-02-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_course_body_en_course_body_ru_course_body_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='name_uz',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
