# Generated by Django 5.0 on 2024-03-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_part_name_en_part_name_ru_part_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
