# Generated by Django 5.0 on 2024-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='last_watched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
