# Generated by Django 5.0 on 2024-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_video_last_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
