# Generated by Django 5.0 on 2024-03-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_video_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
