# Generated by Django 5.0 on 2024-03-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_video_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
    ]
